[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.partitions = huge_app.csv

build_flags =
    -std=gnu++17

board_build.psram_type = opi

lib_deps =
    https://github.com/pschatzmann/arduino-audio-tools
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/DHT sensor library @ ^1.4.4       
    adafruit/Adafruit Unified Sensor @ ^1.1.14 